baseurl = "/"
title = "Clement's blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Clément Davin"
    description = "étudiant en 5ème année à Epita (école d'ingénieur en informatique). actuellement en recherche de stage de février à juillet 2021"
    github = "https://github.com/Nevyr2"
    twitter = "https://twitter.com/davin1_davin"
    email = "clement.davin@epita.fr"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"